### ISSUE TITLE
Create the main page

### ISSUE THREAD

**Issue by dimitri-edel** [caleom/retro-rookies#11]
**Acceptance Criteria**
- [x] The page provides information about the  game 
- [x] The page provides a button for starting the game
- [x] Link to a game tutorial

**Tasks** 
- [x] Navigation bar

**Comment by RQISL** [comment]
I have completed the following, which I checked above on Dimitri's comments, but I have finished the link to a game tutorial; it is just very basic information.
