### ISSUE TITLE
Create User Tutorial

### ISSUE THREAD

**Issue by dimitri-edel** [caleom/retro-rookies#12]
**Acceptance criteria**
- [ ] User can understand how to play the game
- [ ] User can understand the rules of the game

**Tasks**
- [ ] Description of game controls
- [ ] Description of the rules
