### ISSUE TITLE
Selecting a player

### ISSUE THREAD

**Issue by dimitri-edel** [caleom/retro-rookies#15]
**Acceptance criteria**
- [ ] User can select a player
- [ ] Two users can play the game
- [ ] Users can start the game from this view

**Tasks**
- [ ] Create a scene for the Phaser Game Engine for player selection
- [ ] Display images of the characters that users can select from
- [ ] Create an EventEmitter (Phaser) to pass the player selection to the actual Game Scene
