### ISSUE TITLE
Create Sprite Animations

### ISSUE THREAD

**Issue by dimitri-edel** [caleom/retro-rookies#32]
**Acceptance criteria**
- [ ] All characters are fully animated

**Tasks**
- [ ] Load sprites
- [ ] Create sprite animations
- [ ] Assign animations to their corresponding key strokes
